feishu:
  links:
    baseUrl: https://open.feishu.cn/open-apis
    auth:
      target: auth
      tenantToken:
        url: auth/v3/tenant_access_token/internal
    media:
      target: drive
      imageDownload:
        url: drive/v1/medias/{FILE_TOKEN}/download
    sheets:
      target: sheets
      metainfo:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/metainfo
      read:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/values
      readBatch:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/values_batch_get
      insert:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/values_prepend
      write:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/values
      writeBatch:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/values_batch_update
      append:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/values_append
      sheetsBatchUpdate:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/sheets_batch_update
      deleteSeries:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/dimension_range
      appendSeries:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/dimension_range
      insertSeries:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/insert_dimension_range
      writeImage:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/values_image
      style:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/style
      styleBatchUpdate:
        url: sheets/v2/spreadsheets/{SHEET_TOKEN}/styles_batch_update
    workBook:
      target: work
      create:
        url: work/v3/spreadsheets
